#simple IOS config in ansible
---
- name: Sample IOS config for Ansible 2.5
  hosts: ir1835
  gather_facts: no
  vars_prompt:
    - name: loopback_num
      prompt: "What Loopback Number to Configure?"
      private: no

  tasks:
    - name: Create loopback {{loopback_num}}
      ios_interface:
        name: Loopback{{loopback_num}}
        enabled: True
        description: Ansible created LO {{loopback_num}}
    - name: Assign IP to loopback
      ios_l3_interface:
        name: Loopback{{loopback_num}}
        ipv4: 10.111.{{loopback_num}}.1/32
